<a href="https://colab.research.google.com/github/dotsoon/TIL/blob/master/%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy?
- 교제: `파이썬 철저 입문` 214p
- 수치해석용으로 만들어진 모듈이라고 보면 됩니다. 
  - 머신러닝과 같은 데이터 분석을 위해서 만들어진건 아닙니다. 
  - 분야를 가리지 않고, 많이 사용
  - ML/DL에서도 많이 사용
  - 판다스도 자료의 기본 타입은 numpy를 사용 합니다.
- 수학적 계산을 돕기 위해서 만들어진 라이브러리

In [ ]:
# numpy는 일반적으로 np로 줄여서 사용을 하게 됩니다. 
import numpy as np

# 넘파이에서 지원하는 타입
1. array(배열)
  - 주로 통계분석이나, ML/DL에서 사용하는 타입
  - 배열이라고 부릅니다. 
  - 파이썬의 리스트와는 다릅니다.

2. matrix
  - 수학적 계산이 필요한 경우에 많이 사용
  - 수업 시간에는 사용하지 않습니다. 

## 배열의 기본속성
- ndim
  - 배열의 차원
- shape
  - 배열의 크기를 나타내고, 배열의 크기는 원소의 개수와 동일
  - 1차원 배열인 경우에는 행이 1이고, 열이 n인 배열을 의미
  - 배열의 모양은 튜플로 표현이 됩니다. 

### 1차원 배열
- 파이썬의 리스트와 거의 동일

In [ ]:
# 리스트를 원소로 하는 배열 객체 정도로 이해
arr1D = np.array([1, 2, 3, 4])
arr1D

array([1, 2, 3, 4])

자료의 차원을 확인하는 것은 매주 중요합니다. 
- 자료의 차원이 다르면, 알고리즘이 동작하지 않게 됩니다. 
  - 알고리즘을 직접 작성하지는 않고, 잘 만들어진 라이브러리를 이용하게 됩니다. 
  - 자료의 차원을 고려해서 사용을 해야 합니다. 

In [ ]:
# 배열의 차원
arr1D.ndim

1

In [ ]:
# 배열의 크기(모양)
arr1D.shape

(4,)

### 2차원 배열
- 주로 다루게 되는 배열이 2차원이 될 겁니다. 
  - 자료가 대부분 2차원으로 되어있을 겁니다. 
  - 수업시간에도 2차원 배열까지만 확인을 합니다. 
- 리스트와 동일하게, 배열의 원소로 배열을 갖는 배열 정도로 이해 

In [ ]:
arr2D = np.array([
  [1, 2, 3,],
  [4, 5, 6,],
  [7, 8, 9,]
])
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 배열의 차원
arr2D.ndim

2

In [ ]:
# 배열의 크기
# (행, 열)
# 행은 자료의 갯수, 열은 변수의 갯수를 의미하게 됩니다.
arr2D.shape

(3, 3)

# 배열의 특징
- 인덱싱, 슬라이싱(******)
- 팬시 인덱싱
- 배열의 타입
- 넘파에서만 정의되는 특별한 타입

## 배열의 인덱싱과 슬라이싱
- 리스트와 비슷한데, 표현은 다릅니다. 
- 기본적인 개념은 리스트와 동일 
- 교제: 230p

In [ ]:
# 1차원 배열은 리스트와 거의 동일
display( arr1D )
display( arr1D[0] )
display( arr1D[1] )
display( arr1D[-1] )

# out bound bound error를 주의!
display( arr1D[4] )

array([1, 2, 3, 4])

1

2

4

IndexError: ignored

In [ ]:
# 배열도 이터레이블 객체 입니다. 
# 리스트가 아니기 때문에, 리스트에서 제공하는 메소드들은 사용할 수 없습니다. 
for x in arr1D:
  print(x)

1
2
3
4


In [ ]:
# 내장 함수는 사용이 가능합니다. 
display( min( arr1D ) )
display( max( arr1D ))

1

4

In [ ]:
# 슬라이스도 리스트때 처럼 동일하게 사용
display( arr1D[:] )
display( arr1D[::-1] )

array([1, 2, 3, 4])

array([4, 3, 2, 1])

### 2차원 배열의 인덱싱과 슬라이싱
- 인덱싱은 다음과 같이 표현 됩니다. 
$$
  array[행, 열]
$$

- 슬라이스는 행과 열을 각각 정의할 수 있습니다. 

$$
  array[행시작:행끝, 열시작:열끝]
$$

In [ ]:
# 2차원 배열의 인덱스
display( arr2D )
display( arr2D[0, 0] )
display( arr2D[0, 1] )
display( arr2D[1, 1] )

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

1

2

5

In [ ]:
# 배열은 행우선 인덱스를 제공 합니다.
# 판다스와 같은 경우 열 우선 인덱스를 제공
display( arr2D[0] )
display( arr2D[0,])
display( arr2D[0, :])

array([1, 2, 3])

array([1, 2, 3])

array([1, 2, 3])

In [ ]:
# 열만 인덱싱 할 수는 없고, 슬라이스를 활용
# 전체 행에 대해서 슬라이스를 한 이후에 열을 선택
display( arr2D )
display( arr2D[:, 1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([2, 5, 8])

In [ ]:
# 슬라이스를 잘 활용하면 행과 열을 동시에 슬라이스
display( arr2D )
display( arr2D[1:, 1:])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[5, 6],
       [8, 9]])

연습

In [ ]:
# 다음의 코드는 뒤에서 자세하게 설명
arrN = np.arange(1, 31).reshape(3, 10)
arrN

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
# 주어진 배열에서 다음의 수 들을 인덱싱 또는 슬라이스 해보시면 됩니다. 

# 16
display( arrN[1, 5])

# 29
display( arrN[2, 8])

# 14, 15, 16
display( arrN[1, 3:6] )

# 18, 28
display( arrN[1:3, 7])

# 9, 10, 19, 20
display( arrN[:2, 8:])

16

29

array([14, 15, 16])

array([18, 28])

array([[ 9, 10],
       [19, 20]])

In [ ]:
arrn = np.arange(1, 51).reshape(5, 10)
arrn

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
# 14, 15, 16, 17, 24, 25, 26, 27, 34, 35, 36, 37

# 12, 22, 32

## 팬시 인덱싱(배열 인덱싱)
- 인덱스로 배열을 사용
  - 불리언 배열: 불리언(True, False)로 이루어진 배열
  - 정수 배열: 정수로 이루어진 배열

In [ ]:
# 불리언 인덱스
# 배열에서 True에 해당하는 값만 선택
# 불리언 배열을 조건에 부합하는 결과만 선택할 수 있도록 생성해서 사용
display( arr1D )
arr1D[ np.array([True, False, True, False]) ] # 배열의 크기와 인덱스 배열의 크기는 동일

array([1, 2, 3, 4])

array([1, 3])

In [ ]:
# 배열에서 조건에 맞는 값만 검색
display( arr1D > 2 )
display( arr1D[ arr1D > 2 ] )

array([False, False,  True,  True])

array([3, 4])

In [ ]:
# 정수 배열
# 배열에서 원하는 인덱스를 배열로 생성
# 중복 선택이 가능, 배열의 크기와 인덱스 배열의 크기가 달라도 상관이 없습니다. 
display( arr1D )
idx = np.array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 2, 1, 1, 1])
arr1D[ idx ]

array([1, 2, 3, 4])

array([2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 3, 2, 2, 2])

## 배열의 타입
- 리스트와는 다르게 배열은 타입을 가집니다. 
  - 리스트는 여러개의 타입을 원소로 가질 수 있습니다. 
  - 배열은 하나의 타입만 원소로 가질 수 있습니다. 
- 배열은, 배열이 생성될 때, 원소들의 타입을 보고 기본적인 자료의 타입을 결정하게 됩니다. 

In [ ]:
.dtyparr1De

dtype('int64')

파이썬은 숫자를 표현하는데 한계가 없습니다. 
- 라이브러리들은 파이썬만으로만 만들어져있지 않습니다. 
  - 속도를 빠르게 하기 위해서 C, C++ 등의 다른 언어로 만들어진 내용도 파이썬에서는 사용이 가능
  - 자료의 표현도 한계가 발생할 수 있습니다. 

In [ ]:
# 원소의 타입이 여러개라면
# 가장 큰 타입을 기본 타입으로 결정
# 타입이 결정되면, 나머지 값들도 결정된 기본타입을 따르게됩니다. 
arr = np.array([1, 2, 3, 4, 5.0])
display(arr)
display(arr.dtype)

array([1., 2., 3., 4., 5.])

dtype('float64')

In [ ]:
# 배열을 생성할 때, 타입을 직접 결정
arr = np.array([1, 2, 3, 4, 5], dtype=np.float32 )
display( arr )
display( arr.dtype )

array([1., 2., 3., 4., 5.], dtype=float32)

dtype('float32')

> 텐서플로우를 사용하는 경우에는 자료의 차원과 타입에 매우 민감하기때문에, 중요합니다. 

## 넘파이에서만 정의되어 있는 특별한 타입 
- 파이썬은 이런 타입을 갖지 않습니다. 
- inf
  - 표현할 수 없는 값
  - 함수가 수렴하지 않고, 발산하는 경우(inf, -inf)
- NaN(Not a Number)
  - 결측치를 표현(비어있는 값)
  - 값을 표현할 수 없는 경우

In [ ]:
display( type( np.NaN ) )
display( np.array([0]) / np.array([0]) )

float

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan])

In [ ]:
display( type(np.inf) )
display( np.log(0) )

float

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


-inf

# 배열을 생성하는 방법
- 교제: 215p

## 초기화된 배열
- 0과 1만 특별히 취급
- 원소가 전부 0이거나, 전부 1인 경우에는 선형대수에서는 특별하게 취급

In [ ]:
# 0으로 초기화된 배열
np.zeros(10, dtype=np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# 1로 초기화된 배열
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# 0과 1이 아닌 다른값으로 초기화 하고 싶은 경우
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 수열을 생성하는 방법
- range와 같은 역할
- arange
  - 실수(소수)에 대한 수열도 만들 수 있습니다.

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
# 주어진 구간에서, 갯수만큼 균등한 간격으로 수열을 생성
# 마지막 원소를 포함
display( np.linspace(0, 10, 11) )
display( np.linspace(1, 2, 100) )

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

## 무작위 배열을 생성하는 방법
- 랜덤
  - 파이썬(넘파이)은 랜덤은 `균등분포`를 의미합니다.

In [ ]:
# 균등분포를 통해서 정해진 갯수만큼 수를 생성
# 랜덤하기 때문에, 실행할 때마다 매번 다른 값이 생성
np.random.rand(10)

array([0.68354513, 0.63978254, 0.59885927, 0.50423771, 0.71438518,
       0.78034154, 0.94908364, 0.40118007, 0.45439602, 0.94300519])

In [ ]:
# 정수 형태로 무작위수를 생성
np.random.randint(0, 10, size=10)

array([7, 6, 6, 5, 1, 8, 8, 6, 7, 4])

In [ ]:
# 무작위로 생성되는 수를 고정
np.random.seed(123)
np.random.rand(10)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [43]:
# 중복되지 않은 무작위 수를 생성
arr = np.arange(1, 11)
np.random.choice(arr, size=5, replace=False)

array([3, 9, 7, 4, 5])

In [53]:
arr=np.arange(1,45)
np.random.choice(arr, size=6, replace=False)

array([ 4, 33, 38,  8, 28, 43])

랜덤은 표본 추출하는 경우, 샘플링 하는 경우에 주로 사용

로또 번호 생성기
- 로또는 1부터 45까지의 수 중에서 6자리의 수가 무작위로 선택
- 중복은 허용하지 않음